POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name" : "Ohara",
    "email" : "ca.ohara@gmail.com",
    "password" : "123456",
    "role" : "publisher"
}

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email" : "ca.ohara2@gmail.com",
    "password" : "123456"
}

GET http://localhost:5000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjM3MTk0NDkzNjBkNGZhNDUxYTI0ZCIsImlhdCI6MTYwMDM1NTM3OCwiZXhwIjoxNjAyOTQ3Mzc4fQ.pcKa6ygm3VwqC__e0SQhjqxkRjbMJtMA9qnKMtEKooc

