GET http://localhost:5000/api/v1/bootcamps

GET http://localhost:5000/api/v1/bootcamps/radius/02118/10

GET http://localhost:5000/api/v1/bootcamps?location.state=MA&housing=true

GET http://localhost:5000/api/v1/bootcamps?careers[in]=Web Development

GET http://localhost:5000/api/v1/bootcamps?select=name,description

GET http://localhost:5000/api/v1/bootcamps?averageCost[gte]=10000

GET http://localhost:5000/api/v1/bootcamps?select=name,description

GET http://localhost:5000/api/v1/bootcamps?select=name,description&page=2&limit=1

GET http://localhost:5000/api/v1/bootcamps?select=name,description&sort=name

POST http://localhost:5000/api/v1/bootcamps
Content-Type: application/json

POST http://localhost:5000/api/v1/bootcamps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNjM4MTliNzZlZjFiMTMxNDQzMzhhMyIsImlhdCI6MTYwMDM1Njc2MywiZXhwIjoxNjAyOTQ4NzYzfQ.fU8-xUYMQ4wzRL2KbdMbEK6TThe39QTKS7_Ev7Ml_tU

{
  "name": "Devworks Bootcamp TESTS",
	"description": "Devworks is a full stack JavaScript Bootcamp located in the heart of Boston that focuses on the technologies you need to get a high paying job as a web developer",
	"website": "https://devworks.com",
	"phone": "(111) 111-1111",
	"email": "enroll@devworks.com",
	"address": "233 Bay State Rd Boston MA 02215",
	"careers": ["Web Development", "UI/UX", "Business"],
	"housing": true,
	"jobAssistance": true,
	"jobGuarantee": false,
	"acceptGi": true
}

GET http://localhost:5000/api/v1/bootcamps/1

GET http://localhost:5000/api/v1/bootcamps/5f592b7c6a49213ceca21268

GET http://localhost:5000/api/v1/bootcamps/5f592ba97d241b2c60bdccbc

PUT http://localhost:5000/api/v1/bootcamps/5f592b7c6a49213ceca21269
Content-Type: application/json

{
    "careers": [
      "Web Development",
      "UI/UX",
      "Business"
    ],
    "photo": "no-photo.jpg",
    "housing": true,
    "jobAssistance": true,
    "jobGuarantee": false,
    "acceptGi": true,
    "name": "Devworks Bootcamp",
    "description": "Devworks is a full stack JavaScript Bootcamp located in the heart of Boston that focuses on the technologies you need to get a high paying job as a web developer",
    "website": "https://devworks.com",
    "phone": "(111) 111-1111",
    "email": "enroll@devworks.com",
    "address": "233 Bay State Rd Boston MA 02215",
    "createdAt": "2020-09-09T19:22:36.629Z"
  }

DELETE http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0

PUT http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0/photo
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cebolas (1).jpg"
Content-Type: image/jpg

< ./img/cebolas (1).jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
