GET http://localhost:5000/api/v1/courses

GET http://localhost:5000/api/v1/courses?select=title&page=2&limit=1

GET http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0/courses

GET http://localhost:5000/api/v1/courses/5d725cb9c4ded7bcb480eaa1

POST http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0/courses
Content-Type: application/json

{
    "scholarshipAvailabel": false,
    "title": "TESTES",
    "description": "TEAEETSTESTEST ES DSA DSADSAS",
    "weeks": "10",
    "tuition": 499,
    "minimumSkill": "intermediate"
}

PUT http://localhost:5000/api/v1/courses/5f621200252f6856a0685927
Content-Type: application/json

{
    "scholarshipAvailabel": false,
    "title": "TESTES",
    "description": "TESTES TESTES TESTEST TESTES TSETESTES",
    "weeks": "10",
    "tuition": 999,
    "minimumSkill": "intermediate"
}

DELETE http://localhost:5000/api/v1/courses/5f621200252f6856a0685927
