GET http://localhost:5000/api/v1/reviews

GET http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0/reviews

GET http://localhost:5000/api/v1/reviews/5f6a7bd77a792a49f4621060

POST http://localhost:5000/api/v1/bootcamps/5d713995b721c3bb38c1f5d0/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkN2E1MTRiNWQyYzEyYzc0NDliZTA0NCIsImlhdCI6MTYwMDgxMzc4OCwiZXhwIjoxNjAzNDA1Nzg4fQ.jpQm8WeGL4zBqekQaIIqtNG3vL-GC5_EPE6XH3wIqWE
Content-Type: application/json

{
    "title": "TEST!",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque",
    "rating": "10"
}

PUT http://localhost:5000/api/v1/reviews/5f6a7bd77a792a49f4621060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkN2E1MTRiNWQyYzEyYzc0NDliZTA0NCIsImlhdCI6MTYwMDgxMzc4OCwiZXhwIjoxNjAzNDA1Nzg4fQ.jpQm8WeGL4zBqekQaIIqtNG3vL-GC5_EPE6XH3wIqWE
Content-Type: application/json

{
    "title": "test! 12dsadsadsa3"
}

DELETE http://localhost:5000/api/v1/reviews/5f6a7bd77a792a49f4621060
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkN2E1MTRiNWQyYzEyYzc0NDliZTA0NCIsImlhdCI6MTYwMDgxMzc4OCwiZXhwIjoxNjAzNDA1Nzg4fQ.jpQm8WeGL4zBqekQaIIqtNG3vL-GC5_EPE6XH3wIqWE