GET http://localhost:5000/api/v1/bootcamps

GET http://localhost:5000/api/v1/bootcamps/radius/02118/10


POST http://localhost:5000/api/v1/bootcamps
Content-Type: application/json

POST http://localhost:5000/api/v1/bootcamps
Content-Type: application/json

{
    "name": "Devworks Bootcamp",
	"description": "Devworks is a full stack JavaScript Bootcamp located in the heart of Boston that focuses on the technologies you need to get a high paying job as a web developer",
	"website": "https://devworks.com",
	"phone": "(111) 111-1111",
	"email": "enroll@devworks.com",
	"address": "233 Bay State Rd Boston MA 02215",
	"careers": ["Web Development", "UI/UX", "Business"],
	"housing": true,
	"jobAssistance": true,
	"jobGuarantee": false,
	"acceptGi": true
}

GET http://localhost:5000/api/v1/bootcamps/1

GET http://localhost:5000/api/v1/bootcamps/5f592b7c6a49213ceca21268

GET http://localhost:5000/api/v1/bootcamps/5f592ba97d241b2c60bdccbc

PUT http://localhost:5000/api/v1/bootcamps/5f592b7c6a49213ceca21269
Content-Type: application/json

{
    "careers": [
      "Web Development",
      "UI/UX",
      "Business"
    ],
    "photo": "no-photo.jpg",
    "housing": true,
    "jobAssistance": true,
    "jobGuarantee": false,
    "acceptGi": true,
    "name": "Devworks Bootcamp",
    "description": "Devworks is a full stack JavaScript Bootcamp located in the heart of Boston that focuses on the technologies you need to get a high paying job as a web developer",
    "website": "https://devworks.com",
    "phone": "(111) 111-1111",
    "email": "enroll@devworks.com",
    "address": "233 Bay State Rd Boston MA 02215",
    "createdAt": "2020-09-09T19:22:36.629Z"
  }

DELETE http://localhost:5000/api/v1/bootcamps/5f594500fc8fba2d5839479b